var annotated_dup =
[
    [ "GEO", "namespaceGEO.html", [
      [ "FileSystem", "namespaceGEO_1_1FileSystem.html", [
        [ "MemoryNode", "classGEO_1_1FileSystem_1_1MemoryNode.html", "classGEO_1_1FileSystem_1_1MemoryNode" ],
        [ "Node", "classGEO_1_1FileSystem_1_1Node.html", "classGEO_1_1FileSystem_1_1Node" ]
      ] ],
      [ "GLSL", null, [
        [ "GLSLCompileError", "structGEO_1_1GLSL_1_1GLSLCompileError.html", "structGEO_1_1GLSL_1_1GLSLCompileError" ],
        [ "PseudoFileProvider", "classGEO_1_1GLSL_1_1PseudoFileProvider.html", "classGEO_1_1GLSL_1_1PseudoFileProvider" ],
        [ "Source", "classGEO_1_1GLSL_1_1Source.html", "classGEO_1_1GLSL_1_1Source" ]
      ] ],
      [ "Memory", "namespaceGEO_1_1Memory.html", [
        [ "aligned_allocator", "classGEO_1_1Memory_1_1aligned__allocator.html", "classGEO_1_1Memory_1_1aligned__allocator" ],
        [ "PointAlignment", "structGEO_1_1Memory_1_1PointAlignment.html", null ],
        [ "PointAlignment< 2 >", "structGEO_1_1Memory_1_1PointAlignment_3_012_01_4.html", null ],
        [ "PointAlignment< 3 >", "structGEO_1_1Memory_1_1PointAlignment_3_013_01_4.html", null ],
        [ "PointAlignment< 4 >", "structGEO_1_1Memory_1_1PointAlignment_3_014_01_4.html", null ],
        [ "PointAlignment< 6 >", "structGEO_1_1Memory_1_1PointAlignment_3_016_01_4.html", null ],
        [ "PointAlignment< 8 >", "structGEO_1_1Memory_1_1PointAlignment_3_018_01_4.html", null ]
      ] ],
      [ "Numeric", "namespaceGEO_1_1Numeric.html", [
        [ "Limits", "structGEO_1_1Numeric_1_1Limits.html", null ],
        [ "LimitsHelper", "structGEO_1_1Numeric_1_1LimitsHelper.html", null ],
        [ "LimitsHelper< T, true >", "structGEO_1_1Numeric_1_1LimitsHelper_3_01T_00_01true_01_4.html", null ]
      ] ],
      [ "PCK", "namespaceGEO_1_1PCK.html", [
        [ "PredicateStats", "classGEO_1_1PCK_1_1PredicateStats.html", null ]
      ] ],
      [ "Process", "namespaceGEO_1_1Process.html", [
        [ "BasicSpinLockArray", "classGEO_1_1Process_1_1BasicSpinLockArray.html", "classGEO_1_1Process_1_1BasicSpinLockArray" ]
      ] ],
      [ "String", null, [
        [ "ConversionError", "classGEO_1_1String_1_1ConversionError.html", "classGEO_1_1String_1_1ConversionError" ]
      ] ],
      [ "AABB", "classGEO_1_1AABB.html", "classGEO_1_1AABB" ],
      [ "AbstractCSGBuilder", "classGEO_1_1AbstractCSGBuilder.html", "classGEO_1_1AbstractCSGBuilder" ],
      [ "AdaptiveKdTree", "classGEO_1_1AdaptiveKdTree.html", "classGEO_1_1AdaptiveKdTree" ],
      [ "AmbientOcclusionImpl", "classGEO_1_1AmbientOcclusionImpl.html", "classGEO_1_1AmbientOcclusionImpl" ],
      [ "Application", "classGEO_1_1Application.html", "classGEO_1_1Application" ],
      [ "ArcBall", "classGEO_1_1ArcBall.html", "classGEO_1_1ArcBall" ],
      [ "Attribute", "classGEO_1_1Attribute.html", "classGEO_1_1Attribute" ],
      [ "Attribute< bool >", "classGEO_1_1Attribute_3_01bool_01_4.html", "classGEO_1_1Attribute_3_01bool_01_4" ],
      [ "Attribute< vecng< DIM, double > >", "classGEO_1_1Attribute_3_01vecng_3_01DIM_00_01double_01_4_01_4.html", "classGEO_1_1Attribute_3_01vecng_3_01DIM_00_01double_01_4_01_4" ],
      [ "AttributeBase", "classGEO_1_1AttributeBase.html", "classGEO_1_1AttributeBase" ],
      [ "AttributesManager", "classGEO_1_1AttributesManager.html", "classGEO_1_1AttributesManager" ],
      [ "AttributeStore", "classGEO_1_1AttributeStore.html", "classGEO_1_1AttributeStore" ],
      [ "AttributeStoreCreator", "classGEO_1_1AttributeStoreCreator.html", "classGEO_1_1AttributeStoreCreator" ],
      [ "AttributeStoreObserver", "classGEO_1_1AttributeStoreObserver.html", "classGEO_1_1AttributeStoreObserver" ],
      [ "BalancedKdTree", "classGEO_1_1BalancedKdTree.html", "classGEO_1_1BalancedKdTree" ],
      [ "basic_bindex", "structGEO_1_1basic__bindex.html", "structGEO_1_1basic__bindex" ],
      [ "basic_quadindex", "structGEO_1_1basic__quadindex.html", "structGEO_1_1basic__quadindex" ],
      [ "basic_trindex", "structGEO_1_1basic__trindex.html", "structGEO_1_1basic__trindex" ],
      [ "BinaryInputStream", "classGEO_1_1BinaryInputStream.html", "classGEO_1_1BinaryInputStream" ],
      [ "BinaryOutputStream", "classGEO_1_1BinaryOutputStream.html", "classGEO_1_1BinaryOutputStream" ],
      [ "BinaryStream", "classGEO_1_1BinaryStream.html", "classGEO_1_1BinaryStream" ],
      [ "BooleanExpression", "classGEO_1_1BooleanExpression.html", "classGEO_1_1BooleanExpression" ],
      [ "Box", "classGEO_1_1Box.html", "classGEO_1_1Box" ],
      [ "Box2d", "classGEO_1_1Box2d.html", "classGEO_1_1Box2d" ],
      [ "BuildRVDMesh", "classGEO_1_1BuildRVDMesh.html", "classGEO_1_1BuildRVDMesh" ],
      [ "Cavity", "classGEO_1_1Cavity.html", "classGEO_1_1Cavity" ],
      [ "CDT2d", "classGEO_1_1CDT2d.html", "classGEO_1_1CDT2d" ],
      [ "CDTBase2d", "classGEO_1_1CDTBase2d.html", "classGEO_1_1CDTBase2d" ],
      [ "CellDescriptor", "structGEO_1_1CellDescriptor.html", "structGEO_1_1CellDescriptor" ],
      [ "CellStatusArray", "classGEO_1_1CellStatusArray.html", "classGEO_1_1CellStatusArray" ],
      [ "CentroidalVoronoiTesselation", "classGEO_1_1CentroidalVoronoiTesselation.html", "classGEO_1_1CentroidalVoronoiTesselation" ],
      [ "Colormap", "classGEO_1_1Colormap.html", "classGEO_1_1Colormap" ],
      [ "Command", "classGEO_1_1Command.html", "classGEO_1_1Command" ],
      [ "CommandInvoker", "classGEO_1_1CommandInvoker.html", "classGEO_1_1CommandInvoker" ],
      [ "Console", "classGEO_1_1Console.html", "classGEO_1_1Console" ],
      [ "const_index_ptr_in_array", "classGEO_1_1const__index__ptr__in__array.html", null ],
      [ "const_index_ptr_range", "classGEO_1_1const__index__ptr__range.html", null ],
      [ "CoplanarFacets", "classGEO_1_1CoplanarFacets.html", "classGEO_1_1CoplanarFacets" ],
      [ "Counted", "classGEO_1_1Counted.html", "classGEO_1_1Counted" ],
      [ "CSGBuilder", "classGEO_1_1CSGBuilder.html", "classGEO_1_1CSGBuilder" ],
      [ "CSGCompiler", "classGEO_1_1CSGCompiler.html", "classGEO_1_1CSGCompiler" ],
      [ "DebugStream", "classGEO_1_1DebugStream.html", "classGEO_1_1DebugStream" ],
      [ "Delaunay", "classGEO_1_1Delaunay.html", "classGEO_1_1Delaunay" ],
      [ "Delaunay2d", "classGEO_1_1Delaunay2d.html", "classGEO_1_1Delaunay2d" ],
      [ "Delaunay3d", "classGEO_1_1Delaunay3d.html", "classGEO_1_1Delaunay3d" ],
      [ "Delaunay_NearestNeighbors", "classGEO_1_1Delaunay__NearestNeighbors.html", "classGEO_1_1Delaunay__NearestNeighbors" ],
      [ "Environment", "classGEO_1_1Environment.html", "classGEO_1_1Environment" ],
      [ "ExactCDT2d", "classGEO_1_1ExactCDT2d.html", "classGEO_1_1ExactCDT2d" ],
      [ "expansion", "classGEO_1_1expansion.html", "classGEO_1_1expansion" ],
      [ "expansion_nt", "classGEO_1_1expansion__nt.html", "classGEO_1_1expansion__nt" ],
      [ "Factory", "classGEO_1_1Factory.html", "classGEO_1_1Factory" ],
      [ "Factory0", "classGEO_1_1Factory0.html", null ],
      [ "Factory1", "classGEO_1_1Factory1.html", null ],
      [ "FactoryCreator0", "structGEO_1_1FactoryCreator0.html", "structGEO_1_1FactoryCreator0" ],
      [ "FactoryCreator1", "structGEO_1_1FactoryCreator1.html", "structGEO_1_1FactoryCreator1" ],
      [ "FrameBufferObject", "classGEO_1_1FrameBufferObject.html", "classGEO_1_1FrameBufferObject" ],
      [ "FrameField", "classGEO_1_1FrameField.html", "classGEO_1_1FrameField" ],
      [ "FullScreenEffectImpl", "classGEO_1_1FullScreenEffectImpl.html", "classGEO_1_1FullScreenEffectImpl" ],
      [ "FunctionCommandInvoker", "classGEO_1_1FunctionCommandInvoker.html", "classGEO_1_1FunctionCommandInvoker" ],
      [ "GenColor", "classGEO_1_1GenColor.html", "classGEO_1_1GenColor" ],
      [ "GenericLifeCycle", "classGEO_1_1GenericLifeCycle.html", "classGEO_1_1GenericLifeCycle" ],
      [ "geo_declare_image_serializer", "classGEO_1_1geo__declare__image__serializer.html", "classGEO_1_1geo__declare__image__serializer" ],
      [ "geo_register_attribute_type", "classGEO_1_1geo__register__attribute__type.html", "classGEO_1_1geo__register__attribute__type" ],
      [ "GeoFile", "classGEO_1_1GeoFile.html", "classGEO_1_1GeoFile" ],
      [ "GeoFileException", "classGEO_1_1GeoFileException.html", "classGEO_1_1GeoFileException" ],
      [ "Image", "classGEO_1_1Image.html", "classGEO_1_1Image" ],
      [ "ImageLibrary", "classGEO_1_1ImageLibrary.html", "classGEO_1_1ImageLibrary" ],
      [ "ImageRasterizer", "classGEO_1_1ImageRasterizer.html", "classGEO_1_1ImageRasterizer" ],
      [ "ImageSerializer", "classGEO_1_1ImageSerializer.html", "classGEO_1_1ImageSerializer" ],
      [ "ImageSerializer_pgm", "classGEO_1_1ImageSerializer__pgm.html", "classGEO_1_1ImageSerializer__pgm" ],
      [ "ImageSerializer_xpm", "classGEO_1_1ImageSerializer__xpm.html", "classGEO_1_1ImageSerializer__xpm" ],
      [ "ImageSerializerSTB", "classGEO_1_1ImageSerializerSTB.html", "classGEO_1_1ImageSerializerSTB" ],
      [ "ImageSerializerSTBRead", "classGEO_1_1ImageSerializerSTBRead.html", "classGEO_1_1ImageSerializerSTBRead" ],
      [ "ImageSerializerSTBReadWrite", "classGEO_1_1ImageSerializerSTBReadWrite.html", "classGEO_1_1ImageSerializerSTBReadWrite" ],
      [ "index_as_iterator", "classGEO_1_1index__as__iterator.html", null ],
      [ "index_ptr_in_array", "classGEO_1_1index__ptr__in__array.html", null ],
      [ "index_ptr_range", "classGEO_1_1index__ptr__range.html", null ],
      [ "index_range", "classGEO_1_1index__range.html", "classGEO_1_1index__range" ],
      [ "InputGeoFile", "classGEO_1_1InputGeoFile.html", "classGEO_1_1InputGeoFile" ],
      [ "InstanceRepo", "classGEO_1_1InstanceRepo.html", "classGEO_1_1InstanceRepo" ],
      [ "IntegrationSimplex", "classGEO_1_1IntegrationSimplex.html", "classGEO_1_1IntegrationSimplex" ],
      [ "intervalBase", "classGEO_1_1intervalBase.html", null ],
      [ "intervalRN", "classGEO_1_1intervalRN.html", "classGEO_1_1intervalRN" ],
      [ "intervalRU", "classGEO_1_1intervalRU.html", "classGEO_1_1intervalRU" ],
      [ "IsectInfo", "structGEO_1_1IsectInfo.html", "structGEO_1_1IsectInfo" ],
      [ "KdTree", "classGEO_1_1KdTree.html", "classGEO_1_1KdTree" ],
      [ "LifeCycle", "classGEO_1_1LifeCycle.html", "classGEO_1_1LifeCycle" ],
      [ "LineInput", "classGEO_1_1LineInput.html", "classGEO_1_1LineInput" ],
      [ "LocalFeatureSize", "classGEO_1_1LocalFeatureSize.html", "classGEO_1_1LocalFeatureSize" ],
      [ "lua_to", "classGEO_1_1lua__to.html", "classGEO_1_1lua__to" ],
      [ "lua_to< bool >", "classGEO_1_1lua__to_3_01bool_01_4.html", null ],
      [ "lua_to< const char * >", "classGEO_1_1lua__to_3_01const_01char_01_5_01_4.html", null ],
      [ "lua_to< const std::string & >", "classGEO_1_1lua__to_3_01const_01std_1_1string_01_6_01_4.html", null ],
      [ "lua_to< double >", "classGEO_1_1lua__to_3_01double_01_4.html", null ],
      [ "lua_to< float >", "classGEO_1_1lua__to_3_01float_01_4.html", null ],
      [ "lua_to< int >", "classGEO_1_1lua__to_3_01int_01_4.html", null ],
      [ "lua_to< Numeric::int64 >", "classGEO_1_1lua__to_3_01Numeric_1_1int64_01_4.html", null ],
      [ "lua_to< Numeric::uint32 >", "classGEO_1_1lua__to_3_01Numeric_1_1uint32_01_4.html", null ],
      [ "lua_to< Numeric::uint64 >", "classGEO_1_1lua__to_3_01Numeric_1_1uint64_01_4.html", null ],
      [ "lua_to< std::string >", "classGEO_1_1lua__to_3_01std_1_1string_01_4.html", null ],
      [ "lua_wrapper", "classGEO_1_1lua__wrapper.html", null ],
      [ "Matrix", "classGEO_1_1Matrix.html", "classGEO_1_1Matrix" ],
      [ "MemberFunctionCommandInvoker", "classGEO_1_1MemberFunctionCommandInvoker.html", "classGEO_1_1MemberFunctionCommandInvoker" ],
      [ "Mesh", "classGEO_1_1Mesh.html", "classGEO_1_1Mesh" ],
      [ "MeshAABB2d", "classGEO_1_1MeshAABB2d.html", "classGEO_1_1MeshAABB2d" ],
      [ "MeshAABB3d", "classGEO_1_1MeshAABB3d.html", "classGEO_1_1MeshAABB3d" ],
      [ "MeshCellCornersStore", "classGEO_1_1MeshCellCornersStore.html", "classGEO_1_1MeshCellCornersStore" ],
      [ "MeshCellFacetsStore", "classGEO_1_1MeshCellFacetsStore.html", "classGEO_1_1MeshCellFacetsStore" ],
      [ "MeshCells", "classGEO_1_1MeshCells.html", "classGEO_1_1MeshCells" ],
      [ "MeshCellsAABB", "classGEO_1_1MeshCellsAABB.html", "classGEO_1_1MeshCellsAABB" ],
      [ "MeshCellsStore", "classGEO_1_1MeshCellsStore.html", "classGEO_1_1MeshCellsStore" ],
      [ "MeshEdges", "classGEO_1_1MeshEdges.html", "classGEO_1_1MeshEdges" ],
      [ "MeshElements", "classGEO_1_1MeshElements.html", "classGEO_1_1MeshElements" ],
      [ "MeshFacetCornersStore", "classGEO_1_1MeshFacetCornersStore.html", "classGEO_1_1MeshFacetCornersStore" ],
      [ "MeshFacets", "classGEO_1_1MeshFacets.html", "classGEO_1_1MeshFacets" ],
      [ "MeshFacetsAABB", "classGEO_1_1MeshFacetsAABB.html", "classGEO_1_1MeshFacetsAABB" ],
      [ "MeshFacetsAABB2d", "classGEO_1_1MeshFacetsAABB2d.html", "classGEO_1_1MeshFacetsAABB2d" ],
      [ "MeshFacetsStore", "classGEO_1_1MeshFacetsStore.html", "classGEO_1_1MeshFacetsStore" ],
      [ "MeshGfx", "classGEO_1_1MeshGfx.html", "classGEO_1_1MeshGfx" ],
      [ "MeshHalfedges", "classGEO_1_1MeshHalfedges.html", "classGEO_1_1MeshHalfedges" ],
      [ "MeshInTriangle", "classGEO_1_1MeshInTriangle.html", "classGEO_1_1MeshInTriangle" ],
      [ "MeshIOFlags", "classGEO_1_1MeshIOFlags.html", "classGEO_1_1MeshIOFlags" ],
      [ "MeshIOHandler", "classGEO_1_1MeshIOHandler.html", "classGEO_1_1MeshIOHandler" ],
      [ "MeshSplitCallbacks", "classGEO_1_1MeshSplitCallbacks.html", "classGEO_1_1MeshSplitCallbacks" ],
      [ "MeshSubElementsStore", "classGEO_1_1MeshSubElementsStore.html", "classGEO_1_1MeshSubElementsStore" ],
      [ "MeshSurfaceIntersection", "classGEO_1_1MeshSurfaceIntersection.html", "classGEO_1_1MeshSurfaceIntersection" ],
      [ "MeshTetrahedralizeParameters", "structGEO_1_1MeshTetrahedralizeParameters.html", "structGEO_1_1MeshTetrahedralizeParameters" ],
      [ "MeshVertices", "classGEO_1_1MeshVertices.html", "classGEO_1_1MeshVertices" ],
      [ "MonoThreadingThreadManager", "classGEO_1_1MonoThreadingThreadManager.html", "classGEO_1_1MonoThreadingThreadManager" ],
      [ "MorphoMath", "classGEO_1_1MorphoMath.html", "classGEO_1_1MorphoMath" ],
      [ "NearestNeighborSearch", "classGEO_1_1NearestNeighborSearch.html", "classGEO_1_1NearestNeighborSearch" ],
      [ "Optimizer", "classGEO_1_1Optimizer.html", "classGEO_1_1Optimizer" ],
      [ "OutputGeoFile", "classGEO_1_1OutputGeoFile.html", "classGEO_1_1OutputGeoFile" ],
      [ "PackedArrays", "classGEO_1_1PackedArrays.html", "classGEO_1_1PackedArrays" ],
      [ "ParamValidator", "classGEO_1_1ParamValidator.html", "classGEO_1_1ParamValidator" ],
      [ "Periodic", "classGEO_1_1Periodic.html", "classGEO_1_1Periodic" ],
      [ "PeriodicDelaunay3d", "classGEO_1_1PeriodicDelaunay3d.html", "classGEO_1_1PeriodicDelaunay3d" ],
      [ "Plane", "structGEO_1_1Plane.html", "structGEO_1_1Plane" ],
      [ "PrincipalAxes3d", "classGEO_1_1PrincipalAxes3d.html", "classGEO_1_1PrincipalAxes3d" ],
      [ "ProgressClient", "classGEO_1_1ProgressClient.html", "classGEO_1_1ProgressClient" ],
      [ "ProgressTask", "classGEO_1_1ProgressTask.html", "classGEO_1_1ProgressTask" ],
      [ "Quaternion", "classGEO_1_1Quaternion.html", "classGEO_1_1Quaternion" ],
      [ "rationalg", "classGEO_1_1rationalg.html", "classGEO_1_1rationalg" ],
      [ "Ray", "structGEO_1_1Ray.html", "structGEO_1_1Ray" ],
      [ "ReadOnlyScalarAttributeAdapter", "classGEO_1_1ReadOnlyScalarAttributeAdapter.html", "classGEO_1_1ReadOnlyScalarAttributeAdapter" ],
      [ "ReadWriteScalarAttributeAdapter", "classGEO_1_1ReadWriteScalarAttributeAdapter.html", null ],
      [ "RegularWeightedDelaunay2d", "classGEO_1_1RegularWeightedDelaunay2d.html", "classGEO_1_1RegularWeightedDelaunay2d" ],
      [ "RegularWeightedDelaunay3d", "classGEO_1_1RegularWeightedDelaunay3d.html", "classGEO_1_1RegularWeightedDelaunay3d" ],
      [ "RestrictedVoronoiDiagram", "classGEO_1_1RestrictedVoronoiDiagram.html", "classGEO_1_1RestrictedVoronoiDiagram" ],
      [ "RVDCallback", "classGEO_1_1RVDCallback.html", "classGEO_1_1RVDCallback" ],
      [ "RVDMeshBuilder", "classGEO_1_1RVDMeshBuilder.html", "classGEO_1_1RVDMeshBuilder" ],
      [ "RVDPolygonCallback", "classGEO_1_1RVDPolygonCallback.html", "classGEO_1_1RVDPolygonCallback" ],
      [ "RVDPolyhedronCallback", "classGEO_1_1RVDPolyhedronCallback.html", "classGEO_1_1RVDPolyhedronCallback" ],
      [ "RVDVertexMap", "classGEO_1_1RVDVertexMap.html", "classGEO_1_1RVDVertexMap" ],
      [ "ScalarAttributeAdapterBase", "classGEO_1_1ScalarAttributeAdapterBase.html", "classGEO_1_1ScalarAttributeAdapterBase" ],
      [ "SimpleApplication", "classGEO_1_1SimpleApplication.html", "classGEO_1_1SimpleApplication" ],
      [ "SimpleMeshApplication", "classGEO_1_1SimpleMeshApplication.html", "classGEO_1_1SimpleMeshApplication" ],
      [ "SmartPointer", "classGEO_1_1SmartPointer.html", "classGEO_1_1SmartPointer" ],
      [ "StatusBar", "classGEO_1_1StatusBar.html", "classGEO_1_1StatusBar" ],
      [ "Stopwatch", "classGEO_1_1Stopwatch.html", "classGEO_1_1Stopwatch" ],
      [ "StructuringElement", "classGEO_1_1StructuringElement.html", "classGEO_1_1StructuringElement" ],
      [ "SystemEnvironment", "classGEO_1_1SystemEnvironment.html", "classGEO_1_1SystemEnvironment" ],
      [ "TaskCanceled", "structGEO_1_1TaskCanceled.html", "structGEO_1_1TaskCanceled" ],
      [ "TextEditor", "classGEO_1_1TextEditor.html", null ],
      [ "Thread", "classGEO_1_1Thread.html", "classGEO_1_1Thread" ],
      [ "ThreadManager", "classGEO_1_1ThreadManager.html", "classGEO_1_1ThreadManager" ],
      [ "transformed_iterator", "classGEO_1_1transformed__iterator.html", null ],
      [ "transformed_iterator_ref", "classGEO_1_1transformed__iterator__ref.html", null ],
      [ "transformed_range", "classGEO_1_1transformed__range.html", null ],
      [ "transformed_range_ref", "classGEO_1_1transformed__range__ref.html", null ],
      [ "TypedAttributeStore", "classGEO_1_1TypedAttributeStore.html", "classGEO_1_1TypedAttributeStore" ],
      [ "TypedAttributeStoreCreator", "classGEO_1_1TypedAttributeStoreCreator.html", "classGEO_1_1TypedAttributeStoreCreator" ],
      [ "TypedThreadGroup", "classGEO_1_1TypedThreadGroup.html", "classGEO_1_1TypedThreadGroup" ],
      [ "UnsharpMaskingImpl", "classGEO_1_1UnsharpMaskingImpl.html", "classGEO_1_1UnsharpMaskingImpl" ],
      [ "VariableObserver", "classGEO_1_1VariableObserver.html", "classGEO_1_1VariableObserver" ],
      [ "VariableObserverList", "classGEO_1_1VariableObserverList.html", "classGEO_1_1VariableObserverList" ],
      [ "vec2Hg", "classGEO_1_1vec2Hg.html", "classGEO_1_1vec2Hg" ],
      [ "vec2HgLexicoCompare", "classGEO_1_1vec2HgLexicoCompare.html", "classGEO_1_1vec2HgLexicoCompare" ],
      [ "vec3Hg", "classGEO_1_1vec3Hg.html", "classGEO_1_1vec3Hg" ],
      [ "vec3HgLexicoCompare", "classGEO_1_1vec3HgLexicoCompare.html", "classGEO_1_1vec3HgLexicoCompare" ],
      [ "vecng", "classGEO_1_1vecng.html", "classGEO_1_1vecng" ],
      [ "vecng< 2, T >", "classGEO_1_1vecng_3_012_00_01T_01_4.html", "classGEO_1_1vecng_3_012_00_01T_01_4" ],
      [ "vecng< 3, T >", "classGEO_1_1vecng_3_013_00_01T_01_4.html", "classGEO_1_1vecng_3_013_00_01T_01_4" ],
      [ "vecng< 4, T >", "classGEO_1_1vecng_3_014_00_01T_01_4.html", "classGEO_1_1vecng_3_014_00_01T_01_4" ],
      [ "vector", "classGEO_1_1vector.html", "classGEO_1_1vector" ],
      [ "vector< bool >", "classGEO_1_1vector_3_01bool_01_4.html", "classGEO_1_1vector_3_01bool_01_4" ]
    ] ],
    [ "GEOCSG", null, [
      [ "ArgList", "classGEOCSG_1_1ArgList.html", null ],
      [ "Value", "structGEOCSG_1_1Value.html", null ]
    ] ],
    [ "GEOGen", null, [
      [ "ConvexCell", "classGEOGen_1_1ConvexCell.html", "classGEOGen_1_1ConvexCell" ],
      [ "FacetSeed", "structGEOGen_1_1FacetSeed.html", "structGEOGen_1_1FacetSeed" ],
      [ "FacetSeedMarking", "classGEOGen_1_1FacetSeedMarking.html", "classGEOGen_1_1FacetSeedMarking" ],
      [ "PointAllocator", "classGEOGen_1_1PointAllocator.html", "classGEOGen_1_1PointAllocator" ],
      [ "Polygon", "classGEOGen_1_1Polygon.html", "classGEOGen_1_1Polygon" ],
      [ "RestrictedVoronoiDiagram", "classGEOGen_1_1RestrictedVoronoiDiagram.html", "classGEOGen_1_1RestrictedVoronoiDiagram" ],
      [ "small_set", "classGEOGen_1_1small__set.html", "classGEOGen_1_1small__set" ],
      [ "SymbolicVertex", "classGEOGen_1_1SymbolicVertex.html", "classGEOGen_1_1SymbolicVertex" ],
      [ "VectorStack", "classGEOGen_1_1VectorStack.html", "classGEOGen_1_1VectorStack" ],
      [ "Vertex", "classGEOGen_1_1Vertex.html", "classGEOGen_1_1Vertex" ]
    ] ],
    [ "GLUP", null, [
      [ "Context", "classGLUP_1_1Context.html", "classGLUP_1_1Context" ],
      [ "FloatsArrayStateVariable", "classGLUP_1_1FloatsArrayStateVariable.html", "classGLUP_1_1FloatsArrayStateVariable" ],
      [ "ImmediateBuffer", "classGLUP_1_1ImmediateBuffer.html", "classGLUP_1_1ImmediateBuffer" ],
      [ "ImmediateState", "classGLUP_1_1ImmediateState.html", "classGLUP_1_1ImmediateState" ],
      [ "MarchingCell", "classGLUP_1_1MarchingCell.html", "classGLUP_1_1MarchingCell" ],
      [ "MatrixStack", "classGLUP_1_1MatrixStack.html", "classGLUP_1_1MatrixStack" ],
      [ "PrimitiveInfo", "structGLUP_1_1PrimitiveInfo.html", "structGLUP_1_1PrimitiveInfo" ],
      [ "StateVariable", "classGLUP_1_1StateVariable.html", "classGLUP_1_1StateVariable" ],
      [ "StateVariableBase", "classGLUP_1_1StateVariableBase.html", "classGLUP_1_1StateVariableBase" ],
      [ "UniformState", "structGLUP_1_1UniformState.html", null ],
      [ "VectorStateVariable", "classGLUP_1_1VectorStateVariable.html", "classGLUP_1_1VectorStateVariable" ]
    ] ],
    [ "OGF", "namespaceOGF.html", [
      [ "GOMLua", null, [
        [ "GraphiteRef", "structOGF_1_1GOMLua_1_1GraphiteRef.html", null ]
      ] ],
      [ "NL", null, [
        [ "Blas", "classOGF_1_1NL_1_1Blas.html", "classOGF_1_1NL_1_1Blas" ],
        [ "Library", "classOGF_1_1NL_1_1Library.html", "classOGF_1_1NL_1_1Library" ],
        [ "Matrix", "classOGF_1_1NL_1_1Matrix.html", "classOGF_1_1NL_1_1Matrix" ],
        [ "Vector", "classOGF_1_1NL_1_1Vector.html", "classOGF_1_1NL_1_1Vector" ]
      ] ],
      [ "TextUtils", null, [
        [ "Environment", "classOGF_1_1TextUtils_1_1Environment.html", "classOGF_1_1TextUtils_1_1Environment" ]
      ] ],
      [ "AmbientOcclusion", "classOGF_1_1AmbientOcclusion.html", "classOGF_1_1AmbientOcclusion" ],
      [ "Any", "classOGF_1_1Any.html", "classOGF_1_1Any" ],
      [ "Application", "classOGF_1_1Application.html", "classOGF_1_1Application" ],
      [ "ApplicationBase", "classOGF_1_1ApplicationBase.html", "classOGF_1_1ApplicationBase" ],
      [ "ArcBall", "classOGF_1_1ArcBall.html", "classOGF_1_1ArcBall" ],
      [ "ArgList", "classOGF_1_1ArgList.html", "classOGF_1_1ArgList" ],
      [ "BasicFactories", "classOGF_1_1BasicFactories.html", null ],
      [ "BasicFactoriesWithArg", "classOGF_1_1BasicFactoriesWithArg.html", null ],
      [ "BasicFactory", "classOGF_1_1BasicFactory.html", null ],
      [ "BasicFactoryWithArg", "classOGF_1_1BasicFactoryWithArg.html", null ],
      [ "BoolSerializer", "classOGF_1_1BoolSerializer.html", "classOGF_1_1BoolSerializer" ],
      [ "Box2d", "classOGF_1_1Box2d.html", "classOGF_1_1Box2d" ],
      [ "Box3d", "classOGF_1_1Box3d.html", "classOGF_1_1Box3d" ],
      [ "Callable", "classOGF_1_1Callable.html", "classOGF_1_1Callable" ],
      [ "CallableConnection", "classOGF_1_1CallableConnection.html", "classOGF_1_1CallableConnection" ],
      [ "Camera", "classOGF_1_1Camera.html", "classOGF_1_1Camera" ],
      [ "CheckerSphere", "classOGF_1_1CheckerSphere.html", "classOGF_1_1CheckerSphere" ],
      [ "ColormapStyle", "structOGF_1_1ColormapStyle.html", "structOGF_1_1ColormapStyle" ],
      [ "Commands", "classOGF_1_1Commands.html", "classOGF_1_1Commands" ],
      [ "CompositeGrob", "classOGF_1_1CompositeGrob.html", "classOGF_1_1CompositeGrob" ],
      [ "CompositeGrobScope", "classOGF_1_1CompositeGrobScope.html", "classOGF_1_1CompositeGrobScope" ],
      [ "Connection", "classOGF_1_1Connection.html", "classOGF_1_1Connection" ],
      [ "ConnectionList", "classOGF_1_1ConnectionList.html", "classOGF_1_1ConnectionList" ],
      [ "Console", "classOGF_1_1Console.html", "classOGF_1_1Console" ],
      [ "CustomAttributes", "classOGF_1_1CustomAttributes.html", "classOGF_1_1CustomAttributes" ],
      [ "DynamicFactoryMetaClass", "classOGF_1_1DynamicFactoryMetaClass.html", "classOGF_1_1DynamicFactoryMetaClass" ],
      [ "DynamicMetaClass", "classOGF_1_1DynamicMetaClass.html", "classOGF_1_1DynamicMetaClass" ],
      [ "DynamicMetaSlot", "classOGF_1_1DynamicMetaSlot.html", "classOGF_1_1DynamicMetaSlot" ],
      [ "DynamicObject", "classOGF_1_1DynamicObject.html", "classOGF_1_1DynamicObject" ],
      [ "EdgeStyle", "structOGF_1_1EdgeStyle.html", "structOGF_1_1EdgeStyle" ],
      [ "EnumSerializer", "classOGF_1_1EnumSerializer.html", "classOGF_1_1EnumSerializer" ],
      [ "ExplodedViewMeshGrobShader", "classOGF_1_1ExplodedViewMeshGrobShader.html", "classOGF_1_1ExplodedViewMeshGrobShader" ],
      [ "Factory", "classOGF_1_1Factory.html", "classOGF_1_1Factory" ],
      [ "FactoryMetaClass", "classOGF_1_1FactoryMetaClass.html", "classOGF_1_1FactoryMetaClass" ],
      [ "File", "classOGF_1_1File.html", null ],
      [ "FileManager", "classOGF_1_1FileManager.html", "classOGF_1_1FileManager" ],
      [ "Filter", "classOGF_1_1Filter.html", "classOGF_1_1Filter" ],
      [ "FullScreenEffect", "classOGF_1_1FullScreenEffect.html", "classOGF_1_1FullScreenEffect" ],
      [ "GenericBasicFactory", "classOGF_1_1GenericBasicFactory.html", null ],
      [ "GenericBasicFactoryWithArg", "classOGF_1_1GenericBasicFactoryWithArg.html", null ],
      [ "GenericSerializer", "classOGF_1_1GenericSerializer.html", "classOGF_1_1GenericSerializer" ],
      [ "GenericSerializer< ArgList >", "classOGF_1_1GenericSerializer_3_01ArgList_01_4.html", null ],
      [ "GlobalScope", "classOGF_1_1GlobalScope.html", "classOGF_1_1GlobalScope" ],
      [ "GomCodeGenerator", "classOGF_1_1GomCodeGenerator.html", "classOGF_1_1GomCodeGenerator" ],
      [ "Grob", "classOGF_1_1Grob.html", "classOGF_1_1Grob" ],
      [ "GrobLight", "classOGF_1_1GrobLight.html", "classOGF_1_1GrobLight" ],
      [ "GrobPan", "classOGF_1_1GrobPan.html", "classOGF_1_1GrobPan" ],
      [ "GrobSelect", "classOGF_1_1GrobSelect.html", "classOGF_1_1GrobSelect" ],
      [ "IconRepository", "classOGF_1_1IconRepository.html", "classOGF_1_1IconRepository" ],
      [ "InputGraphiteFile", "classOGF_1_1InputGraphiteFile.html", "classOGF_1_1InputGraphiteFile" ],
      [ "Interface", "classOGF_1_1Interface.html", "classOGF_1_1Interface" ],
      [ "InterfaceScope", "classOGF_1_1InterfaceScope.html", "classOGF_1_1InterfaceScope" ],
      [ "Interpreter", "classOGF_1_1Interpreter.html", "classOGF_1_1Interpreter" ],
      [ "LuaCallable", "classOGF_1_1LuaCallable.html", "classOGF_1_1LuaCallable" ],
      [ "LuaFile", "classOGF_1_1LuaFile.html", null ],
      [ "LuaGrob", "classOGF_1_1LuaGrob.html", "classOGF_1_1LuaGrob" ],
      [ "LuaGrobCommands", "classOGF_1_1LuaGrobCommands.html", "classOGF_1_1LuaGrobCommands" ],
      [ "LuaGrobProgramCommands", "classOGF_1_1LuaGrobProgramCommands.html", "classOGF_1_1LuaGrobProgramCommands" ],
      [ "LuaGrobShader", "classOGF_1_1LuaGrobShader.html", "classOGF_1_1LuaGrobShader" ],
      [ "LuaGrobShaderCommands", "classOGF_1_1LuaGrobShaderCommands.html", "classOGF_1_1LuaGrobShaderCommands" ],
      [ "LuaInterpreter", "classOGF_1_1LuaInterpreter.html", "classOGF_1_1LuaInterpreter" ],
      [ "MeshGrob", "classOGF_1_1MeshGrob.html", "classOGF_1_1MeshGrob" ],
      [ "MeshGrobAttributesCommands", "classOGF_1_1MeshGrobAttributesCommands.html", "classOGF_1_1MeshGrobAttributesCommands" ],
      [ "MeshGrobCommands", "classOGF_1_1MeshGrobCommands.html", "classOGF_1_1MeshGrobCommands" ],
      [ "MeshGrobConnectDisconnectEdges", "classOGF_1_1MeshGrobConnectDisconnectEdges.html", "classOGF_1_1MeshGrobConnectDisconnectEdges" ],
      [ "MeshGrobConnectEdges", "classOGF_1_1MeshGrobConnectEdges.html", "classOGF_1_1MeshGrobConnectEdges" ],
      [ "MeshGrobCopyComponent", "classOGF_1_1MeshGrobCopyComponent.html", "classOGF_1_1MeshGrobCopyComponent" ],
      [ "MeshGrobCreateCenterVertex", "classOGF_1_1MeshGrobCreateCenterVertex.html", "classOGF_1_1MeshGrobCreateCenterVertex" ],
      [ "MeshGrobCreateEdge", "classOGF_1_1MeshGrobCreateEdge.html", "classOGF_1_1MeshGrobCreateEdge" ],
      [ "MeshGrobDeleteEdge", "classOGF_1_1MeshGrobDeleteEdge.html", "classOGF_1_1MeshGrobDeleteEdge" ],
      [ "MeshGrobEditCenterVertex", "classOGF_1_1MeshGrobEditCenterVertex.html", "classOGF_1_1MeshGrobEditCenterVertex" ],
      [ "MeshGrobEditEdge", "classOGF_1_1MeshGrobEditEdge.html", "classOGF_1_1MeshGrobEditEdge" ],
      [ "MeshGrobEditFacetEdge", "classOGF_1_1MeshGrobEditFacetEdge.html", "classOGF_1_1MeshGrobEditFacetEdge" ],
      [ "MeshGrobEditHole", "classOGF_1_1MeshGrobEditHole.html", "classOGF_1_1MeshGrobEditHole" ],
      [ "MeshGrobEditor", "classOGF_1_1MeshGrobEditor.html", "classOGF_1_1MeshGrobEditor" ],
      [ "MeshGrobFillHole", "classOGF_1_1MeshGrobFillHole.html", "classOGF_1_1MeshGrobFillHole" ],
      [ "MeshGrobFiltersCommands", "classOGF_1_1MeshGrobFiltersCommands.html", "classOGF_1_1MeshGrobFiltersCommands" ],
      [ "MeshGrobFlipComponent", "classOGF_1_1MeshGrobFlipComponent.html", "classOGF_1_1MeshGrobFlipComponent" ],
      [ "MeshGrobGlueEdges", "classOGF_1_1MeshGrobGlueEdges.html", "classOGF_1_1MeshGrobGlueEdges" ],
      [ "MeshGrobGlueUnglueEdges", "classOGF_1_1MeshGrobGlueUnglueEdges.html", "classOGF_1_1MeshGrobGlueUnglueEdges" ],
      [ "MeshGrobJoinFacets", "classOGF_1_1MeshGrobJoinFacets.html", "classOGF_1_1MeshGrobJoinFacets" ],
      [ "MeshGrobKeepOrRemoveComponent", "classOGF_1_1MeshGrobKeepOrRemoveComponent.html", "classOGF_1_1MeshGrobKeepOrRemoveComponent" ],
      [ "MeshGrobMeshCommands", "classOGF_1_1MeshGrobMeshCommands.html", "classOGF_1_1MeshGrobMeshCommands" ],
      [ "MeshGrobMoveSubset", "classOGF_1_1MeshGrobMoveSubset.html", "classOGF_1_1MeshGrobMoveSubset" ],
      [ "MeshGrobPaint", "classOGF_1_1MeshGrobPaint.html", "classOGF_1_1MeshGrobPaint" ],
      [ "MeshGrobPaintConnected", "classOGF_1_1MeshGrobPaintConnected.html", "classOGF_1_1MeshGrobPaintConnected" ],
      [ "MeshGrobPaintFreeform", "classOGF_1_1MeshGrobPaintFreeform.html", "classOGF_1_1MeshGrobPaintFreeform" ],
      [ "MeshGrobPaintRect", "classOGF_1_1MeshGrobPaintRect.html", "classOGF_1_1MeshGrobPaintRect" ],
      [ "MeshGrobPaintTool", "classOGF_1_1MeshGrobPaintTool.html", "classOGF_1_1MeshGrobPaintTool" ],
      [ "MeshGrobPointsCommands", "classOGF_1_1MeshGrobPointsCommands.html", "classOGF_1_1MeshGrobPointsCommands" ],
      [ "MeshGrobProbe", "classOGF_1_1MeshGrobProbe.html", "classOGF_1_1MeshGrobProbe" ],
      [ "MeshGrobRemoveCenterVertex", "classOGF_1_1MeshGrobRemoveCenterVertex.html", "classOGF_1_1MeshGrobRemoveCenterVertex" ],
      [ "MeshGrobRemoveComponent", "classOGF_1_1MeshGrobRemoveComponent.html", "classOGF_1_1MeshGrobRemoveComponent" ],
      [ "MeshGrobRemoveFacet", "classOGF_1_1MeshGrobRemoveFacet.html", "classOGF_1_1MeshGrobRemoveFacet" ],
      [ "MeshGrobRemoveIncidentFacets", "classOGF_1_1MeshGrobRemoveIncidentFacets.html", "classOGF_1_1MeshGrobRemoveIncidentFacets" ],
      [ "MeshGrobResizeSubset", "classOGF_1_1MeshGrobResizeSubset.html", "classOGF_1_1MeshGrobResizeSubset" ],
      [ "MeshGrobRotateSubset", "classOGF_1_1MeshGrobRotateSubset.html", "classOGF_1_1MeshGrobRotateSubset" ],
      [ "MeshGrobRuler", "classOGF_1_1MeshGrobRuler.html", "classOGF_1_1MeshGrobRuler" ],
      [ "MeshGrobScrollResizeSubset", "classOGF_1_1MeshGrobScrollResizeSubset.html", "classOGF_1_1MeshGrobScrollResizeSubset" ],
      [ "MeshGrobSelectionsCommands", "classOGF_1_1MeshGrobSelectionsCommands.html", "classOGF_1_1MeshGrobSelectionsCommands" ],
      [ "MeshGrobSelectUnselectVertex", "classOGF_1_1MeshGrobSelectUnselectVertex.html", "classOGF_1_1MeshGrobSelectUnselectVertex" ],
      [ "MeshGrobSelectVertex", "classOGF_1_1MeshGrobSelectVertex.html", "classOGF_1_1MeshGrobSelectVertex" ],
      [ "MeshGrobShader", "classOGF_1_1MeshGrobShader.html", "classOGF_1_1MeshGrobShader" ],
      [ "MeshGrobShapesCommands", "classOGF_1_1MeshGrobShapesCommands.html", "classOGF_1_1MeshGrobShapesCommands" ],
      [ "MeshGrobSpectralCommands", "classOGF_1_1MeshGrobSpectralCommands.html", "classOGF_1_1MeshGrobSpectralCommands" ],
      [ "MeshGrobSplitFacet", "classOGF_1_1MeshGrobSplitFacet.html", "classOGF_1_1MeshGrobSplitFacet" ],
      [ "MeshGrobSurfaceCommands", "classOGF_1_1MeshGrobSurfaceCommands.html", "classOGF_1_1MeshGrobSurfaceCommands" ],
      [ "MeshGrobTool", "classOGF_1_1MeshGrobTool.html", "classOGF_1_1MeshGrobTool" ],
      [ "MeshGrobTransformComponent", "classOGF_1_1MeshGrobTransformComponent.html", "classOGF_1_1MeshGrobTransformComponent" ],
      [ "MeshGrobTransformFacet", "classOGF_1_1MeshGrobTransformFacet.html", "classOGF_1_1MeshGrobTransformFacet" ],
      [ "MeshGrobTransformSubset", "classOGF_1_1MeshGrobTransformSubset.html", "classOGF_1_1MeshGrobTransformSubset" ],
      [ "MeshGrobTransformTool", "classOGF_1_1MeshGrobTransformTool.html", "classOGF_1_1MeshGrobTransformTool" ],
      [ "MeshGrobUnglueEdges", "classOGF_1_1MeshGrobUnglueEdges.html", "classOGF_1_1MeshGrobUnglueEdges" ],
      [ "MeshGrobUnselectVertex", "classOGF_1_1MeshGrobUnselectVertex.html", "classOGF_1_1MeshGrobUnselectVertex" ],
      [ "MeshGrobVisibilityCommands", "classOGF_1_1MeshGrobVisibilityCommands.html", "classOGF_1_1MeshGrobVisibilityCommands" ],
      [ "MeshGrobVolumeCommands", "classOGF_1_1MeshGrobVolumeCommands.html", "classOGF_1_1MeshGrobVolumeCommands" ],
      [ "MeshGrobZipEdges", "classOGF_1_1MeshGrobZipEdges.html", "classOGF_1_1MeshGrobZipEdges" ],
      [ "MeshGrobZipUnzipEdges", "classOGF_1_1MeshGrobZipUnzipEdges.html", "classOGF_1_1MeshGrobZipUnzipEdges" ],
      [ "Meta", "classOGF_1_1Meta.html", "classOGF_1_1Meta" ],
      [ "MetaArg", "classOGF_1_1MetaArg.html", "classOGF_1_1MetaArg" ],
      [ "MetaBuiltinType", "classOGF_1_1MetaBuiltinType.html", "classOGF_1_1MetaBuiltinType" ],
      [ "MetaClass", "classOGF_1_1MetaClass.html", "classOGF_1_1MetaClass" ],
      [ "MetaConstructor", "classOGF_1_1MetaConstructor.html", "classOGF_1_1MetaConstructor" ],
      [ "MetaEnum", "classOGF_1_1MetaEnum.html", "classOGF_1_1MetaEnum" ],
      [ "MetaInformation", "classOGF_1_1MetaInformation.html", "classOGF_1_1MetaInformation" ],
      [ "MetaMember", "classOGF_1_1MetaMember.html", "classOGF_1_1MetaMember" ],
      [ "MetaMethod", "classOGF_1_1MetaMethod.html", "classOGF_1_1MetaMethod" ],
      [ "MetaMethodGetProperty", "classOGF_1_1MetaMethodGetProperty.html", "classOGF_1_1MetaMethodGetProperty" ],
      [ "MetaMethodSetProperty", "classOGF_1_1MetaMethodSetProperty.html", "classOGF_1_1MetaMethodSetProperty" ],
      [ "MetaProperty", "classOGF_1_1MetaProperty.html", "classOGF_1_1MetaProperty" ],
      [ "MetaSignal", "classOGF_1_1MetaSignal.html", "classOGF_1_1MetaSignal" ],
      [ "MetaSlot", "classOGF_1_1MetaSlot.html", "classOGF_1_1MetaSlot" ],
      [ "MetaType", "classOGF_1_1MetaType.html", "classOGF_1_1MetaType" ],
      [ "MetaTypesScope", "classOGF_1_1MetaTypesScope.html", "classOGF_1_1MetaTypesScope" ],
      [ "Module", "classOGF_1_1Module.html", "classOGF_1_1Module" ],
      [ "ModuleMaker", "classOGF_1_1ModuleMaker.html", "classOGF_1_1ModuleMaker" ],
      [ "ModuleManager", "classOGF_1_1ModuleManager.html", "classOGF_1_1ModuleManager" ],
      [ "MultiTool", "classOGF_1_1MultiTool.html", "classOGF_1_1MultiTool" ],
      [ "Name", "classOGF_1_1Name.html", "classOGF_1_1Name" ],
      [ "NameBase", "classOGF_1_1NameBase.html", null ],
      [ "Node", "classOGF_1_1Node.html", "classOGF_1_1Node" ],
      [ "Object", "classOGF_1_1Object.html", "classOGF_1_1Object" ],
      [ "ogf_declare_abstract_class", "classOGF_1_1ogf__declare__abstract__class.html", "classOGF_1_1ogf__declare__abstract__class" ],
      [ "ogf_declare_builtin_type", "classOGF_1_1ogf__declare__builtin__type.html", "classOGF_1_1ogf__declare__builtin__type" ],
      [ "ogf_declare_builtin_type< bool >", "classOGF_1_1ogf__declare__builtin__type_3_01bool_01_4.html", "classOGF_1_1ogf__declare__builtin__type_3_01bool_01_4" ],
      [ "ogf_declare_builtin_type< std::string >", "classOGF_1_1ogf__declare__builtin__type_3_01std_1_1string_01_4.html", "classOGF_1_1ogf__declare__builtin__type_3_01std_1_1string_01_4" ],
      [ "ogf_declare_builtin_type< void >", "classOGF_1_1ogf__declare__builtin__type_3_01void_01_4.html", "classOGF_1_1ogf__declare__builtin__type_3_01void_01_4" ],
      [ "ogf_declare_class", "classOGF_1_1ogf__declare__class.html", "classOGF_1_1ogf__declare__class" ],
      [ "ogf_declare_enum", "classOGF_1_1ogf__declare__enum.html", "classOGF_1_1ogf__declare__enum" ],
      [ "ogf_declare_pointer_type", "classOGF_1_1ogf__declare__pointer__type.html", "classOGF_1_1ogf__declare__pointer__type" ],
      [ "ogf_meta", "classOGF_1_1ogf__meta.html", null ],
      [ "ogf_register_abstract_grob_type", "classOGF_1_1ogf__register__abstract__grob__type.html", "classOGF_1_1ogf__register__abstract__grob__type" ],
      [ "ogf_register_full_screen_effect", "classOGF_1_1ogf__register__full__screen__effect.html", "classOGF_1_1ogf__register__full__screen__effect" ],
      [ "ogf_register_grob_commands", "classOGF_1_1ogf__register__grob__commands.html", "classOGF_1_1ogf__register__grob__commands" ],
      [ "ogf_register_grob_interface", "classOGF_1_1ogf__register__grob__interface.html", "classOGF_1_1ogf__register__grob__interface" ],
      [ "ogf_register_grob_read_file_extension", "classOGF_1_1ogf__register__grob__read__file__extension.html", "classOGF_1_1ogf__register__grob__read__file__extension" ],
      [ "ogf_register_grob_shader", "classOGF_1_1ogf__register__grob__shader.html", "classOGF_1_1ogf__register__grob__shader" ],
      [ "ogf_register_grob_tool", "classOGF_1_1ogf__register__grob__tool.html", "classOGF_1_1ogf__register__grob__tool" ],
      [ "ogf_register_grob_type", "classOGF_1_1ogf__register__grob__type.html", "classOGF_1_1ogf__register__grob__type" ],
      [ "ogf_register_grob_write_file_extension", "classOGF_1_1ogf__register__grob__write__file__extension.html", "classOGF_1_1ogf__register__grob__write__file__extension" ],
      [ "OutputGraphiteFile", "classOGF_1_1OutputGraphiteFile.html", "classOGF_1_1OutputGraphiteFile" ],
      [ "Overlay", "classOGF_1_1Overlay.html", "classOGF_1_1Overlay" ],
      [ "ParamMeshGrobShader", "classOGF_1_1ParamMeshGrobShader.html", "classOGF_1_1ParamMeshGrobShader" ],
      [ "PDBMeshGrobShader", "classOGF_1_1PDBMeshGrobShader.html", "classOGF_1_1PDBMeshGrobShader" ],
      [ "PlainFullScreenEffect", "classOGF_1_1PlainFullScreenEffect.html", "classOGF_1_1PlainFullScreenEffect" ],
      [ "PlainLuaGrobShader", "classOGF_1_1PlainLuaGrobShader.html", "classOGF_1_1PlainLuaGrobShader" ],
      [ "PlainMeshGrobShader", "classOGF_1_1PlainMeshGrobShader.html", "classOGF_1_1PlainMeshGrobShader" ],
      [ "PlainVoxelGrobShader", "classOGF_1_1PlainVoxelGrobShader.html", "classOGF_1_1PlainVoxelGrobShader" ],
      [ "PointerSerializer", "classOGF_1_1PointerSerializer.html", "classOGF_1_1PointerSerializer" ],
      [ "PointStyle", "structOGF_1_1PointStyle.html", "structOGF_1_1PointStyle" ],
      [ "RayPick", "structOGF_1_1RayPick.html", "structOGF_1_1RayPick" ],
      [ "RayPicker", "classOGF_1_1RayPicker.html", "classOGF_1_1RayPicker" ],
      [ "RenderArea", "classOGF_1_1RenderArea.html", "classOGF_1_1RenderArea" ],
      [ "RenderingContext", "classOGF_1_1RenderingContext.html", "classOGF_1_1RenderingContext" ],
      [ "Request", "classOGF_1_1Request.html", "classOGF_1_1Request" ],
      [ "SceneGraph", "classOGF_1_1SceneGraph.html", "classOGF_1_1SceneGraph" ],
      [ "SceneGraphCommands", "classOGF_1_1SceneGraphCommands.html", "classOGF_1_1SceneGraphCommands" ],
      [ "SceneGraphDevelCommands", "classOGF_1_1SceneGraphDevelCommands.html", "classOGF_1_1SceneGraphDevelCommands" ],
      [ "SceneGraphLibrary", "classOGF_1_1SceneGraphLibrary.html", "classOGF_1_1SceneGraphLibrary" ],
      [ "SceneGraphSceneCommands", "classOGF_1_1SceneGraphSceneCommands.html", "classOGF_1_1SceneGraphSceneCommands" ],
      [ "SceneGraphShaderManager", "classOGF_1_1SceneGraphShaderManager.html", "classOGF_1_1SceneGraphShaderManager" ],
      [ "SceneGraphToolsManager", "classOGF_1_1SceneGraphToolsManager.html", "classOGF_1_1SceneGraphToolsManager" ],
      [ "Scope", "classOGF_1_1Scope.html", "classOGF_1_1Scope" ],
      [ "Serializer", "classOGF_1_1Serializer.html", "classOGF_1_1Serializer" ],
      [ "Shader", "classOGF_1_1Shader.html", "classOGF_1_1Shader" ],
      [ "ShaderManager", "classOGF_1_1ShaderManager.html", "classOGF_1_1ShaderManager" ],
      [ "SkinImGUIRenderingContext", "classOGF_1_1SkinImGUIRenderingContext.html", "classOGF_1_1SkinImGUIRenderingContext" ],
      [ "SlotConnection", "classOGF_1_1SlotConnection.html", "classOGF_1_1SlotConnection" ],
      [ "StringSerializer", "classOGF_1_1StringSerializer.html", "classOGF_1_1StringSerializer" ],
      [ "SurfaceStyle", "structOGF_1_1SurfaceStyle.html", "structOGF_1_1SurfaceStyle" ],
      [ "TextEditor", "classOGF_1_1TextEditor.html", "classOGF_1_1TextEditor" ],
      [ "Texture", "classOGF_1_1Texture.html", "classOGF_1_1Texture" ],
      [ "Tool", "classOGF_1_1Tool.html", "classOGF_1_1Tool" ],
      [ "ToolsManager", "classOGF_1_1ToolsManager.html", "classOGF_1_1ToolsManager" ],
      [ "Transform3d", "classOGF_1_1Transform3d.html", "classOGF_1_1Transform3d" ],
      [ "Translation", "classOGF_1_1Translation.html", "classOGF_1_1Translation" ],
      [ "UnsharpMasking", "classOGF_1_1UnsharpMasking.html", "classOGF_1_1UnsharpMasking" ],
      [ "VoxelGrob", "classOGF_1_1VoxelGrob.html", "classOGF_1_1VoxelGrob" ],
      [ "VoxelGrobAttributesCommands", "classOGF_1_1VoxelGrobAttributesCommands.html", "classOGF_1_1VoxelGrobAttributesCommands" ],
      [ "VoxelGrobCommands", "classOGF_1_1VoxelGrobCommands.html", "classOGF_1_1VoxelGrobCommands" ],
      [ "VoxelGrobEditor", "classOGF_1_1VoxelGrobEditor.html", "classOGF_1_1VoxelGrobEditor" ],
      [ "VoxelGrobShader", "classOGF_1_1VoxelGrobShader.html", "classOGF_1_1VoxelGrobShader" ]
    ] ],
    [ "VBW", null, [
      [ "ConvexCell", "classVBW_1_1ConvexCell.html", "classVBW_1_1ConvexCell" ],
      [ "Triangle", "structVBW_1_1Triangle.html", null ],
      [ "TriangleWithFlags", "structVBW_1_1TriangleWithFlags.html", null ]
    ] ],
    [ "Ray", "structRay.html", null ],
    [ "UniformState", "structUniformState.html", null ],
    [ "VSUniformState", "structVSUniformState.html", null ]
];