var namespaceGEO =
[
    [ "FileSystem", "namespaceGEO_1_1FileSystem.html", "namespaceGEO_1_1FileSystem" ],
    [ "GLSL", null, [
      [ "GLSLCompileError", "structGEO_1_1GLSL_1_1GLSLCompileError.html", "structGEO_1_1GLSL_1_1GLSLCompileError" ],
      [ "PseudoFileProvider", "classGEO_1_1GLSL_1_1PseudoFileProvider.html", "classGEO_1_1GLSL_1_1PseudoFileProvider" ],
      [ "Source", "classGEO_1_1GLSL_1_1Source.html", "classGEO_1_1GLSL_1_1Source" ]
    ] ],
    [ "Memory", "namespaceGEO_1_1Memory.html", "namespaceGEO_1_1Memory" ],
    [ "Numeric", "namespaceGEO_1_1Numeric.html", "namespaceGEO_1_1Numeric" ],
    [ "String", null, [
      [ "ConversionError", "classGEO_1_1String_1_1ConversionError.html", "classGEO_1_1String_1_1ConversionError" ]
    ] ],
    [ "AABB", "classGEO_1_1AABB.html", "classGEO_1_1AABB" ],
    [ "AdaptiveKdTree", "classGEO_1_1AdaptiveKdTree.html", "classGEO_1_1AdaptiveKdTree" ],
    [ "AmbientOcclusionImpl", "classGEO_1_1AmbientOcclusionImpl.html", "classGEO_1_1AmbientOcclusionImpl" ],
    [ "Application", "classGEO_1_1Application.html", "classGEO_1_1Application" ],
    [ "ArcBall", "classGEO_1_1ArcBall.html", "classGEO_1_1ArcBall" ],
    [ "Attribute", "classGEO_1_1Attribute.html", "classGEO_1_1Attribute" ],
    [ "Attribute< bool >", "classGEO_1_1Attribute_3_01bool_01_4.html", "classGEO_1_1Attribute_3_01bool_01_4" ],
    [ "AttributeBase", "classGEO_1_1AttributeBase.html", "classGEO_1_1AttributeBase" ],
    [ "AttributesManager", "classGEO_1_1AttributesManager.html", "classGEO_1_1AttributesManager" ],
    [ "AttributeStore", "classGEO_1_1AttributeStore.html", "classGEO_1_1AttributeStore" ],
    [ "AttributeStoreCreator", "classGEO_1_1AttributeStoreCreator.html", "classGEO_1_1AttributeStoreCreator" ],
    [ "AttributeStoreObserver", "classGEO_1_1AttributeStoreObserver.html", "classGEO_1_1AttributeStoreObserver" ],
    [ "AxisPermutation", "structGEO_1_1AxisPermutation.html", "structGEO_1_1AxisPermutation" ],
    [ "BalancedKdTree", "classGEO_1_1BalancedKdTree.html", "classGEO_1_1BalancedKdTree" ],
    [ "basic_bindex", "structGEO_1_1basic__bindex.html", "structGEO_1_1basic__bindex" ],
    [ "basic_quadindex", "structGEO_1_1basic__quadindex.html", "structGEO_1_1basic__quadindex" ],
    [ "basic_trindex", "structGEO_1_1basic__trindex.html", "structGEO_1_1basic__trindex" ],
    [ "Basis3d", "structGEO_1_1Basis3d.html", "structGEO_1_1Basis3d" ],
    [ "BBox", "structGEO_1_1BBox.html", "structGEO_1_1BBox" ],
    [ "BBox1", "structGEO_1_1BBox1.html", "structGEO_1_1BBox1" ],
    [ "BinaryInputStream", "classGEO_1_1BinaryInputStream.html", "classGEO_1_1BinaryInputStream" ],
    [ "BinaryOutputStream", "classGEO_1_1BinaryOutputStream.html", "classGEO_1_1BinaryOutputStream" ],
    [ "BinaryStream", "classGEO_1_1BinaryStream.html", "classGEO_1_1BinaryStream" ],
    [ "Box", "classGEO_1_1Box.html", "classGEO_1_1Box" ],
    [ "Box2d", "classGEO_1_1Box2d.html", "classGEO_1_1Box2d" ],
    [ "BuildRVDMesh", "classGEO_1_1BuildRVDMesh.html", "classGEO_1_1BuildRVDMesh" ],
    [ "Cavity", "classGEO_1_1Cavity.html", "classGEO_1_1Cavity" ],
    [ "CellDescriptor", "structGEO_1_1CellDescriptor.html", "structGEO_1_1CellDescriptor" ],
    [ "CentroidalVoronoiTesselation", "classGEO_1_1CentroidalVoronoiTesselation.html", "classGEO_1_1CentroidalVoronoiTesselation" ],
    [ "Chart", "structGEO_1_1Chart.html", "structGEO_1_1Chart" ],
    [ "Coeff", "structGEO_1_1Coeff.html", "structGEO_1_1Coeff" ],
    [ "Colormap", "classGEO_1_1Colormap.html", "classGEO_1_1Colormap" ],
    [ "Command", "classGEO_1_1Command.html", "classGEO_1_1Command" ],
    [ "CommandInvoker", "classGEO_1_1CommandInvoker.html", "classGEO_1_1CommandInvoker" ],
    [ "Console", "classGEO_1_1Console.html", "classGEO_1_1Console" ],
    [ "CoTan3D", "structGEO_1_1CoTan3D.html", "structGEO_1_1CoTan3D" ],
    [ "Counted", "classGEO_1_1Counted.html", "classGEO_1_1Counted" ],
    [ "Delaunay", "classGEO_1_1Delaunay.html", "classGEO_1_1Delaunay" ],
    [ "Delaunay2d", "classGEO_1_1Delaunay2d.html", "classGEO_1_1Delaunay2d" ],
    [ "Delaunay3d", "classGEO_1_1Delaunay3d.html", "classGEO_1_1Delaunay3d" ],
    [ "Delaunay_NearestNeighbors", "classGEO_1_1Delaunay__NearestNeighbors.html", "classGEO_1_1Delaunay__NearestNeighbors" ],
    [ "DynamicHBoxes", "structGEO_1_1DynamicHBoxes.html", "structGEO_1_1DynamicHBoxes" ],
    [ "Environment", "classGEO_1_1Environment.html", "classGEO_1_1Environment" ],
    [ "expansion", "classGEO_1_1expansion.html", "classGEO_1_1expansion" ],
    [ "expansion_nt", "classGEO_1_1expansion__nt.html", "classGEO_1_1expansion__nt" ],
    [ "FacetIntersect", "structGEO_1_1FacetIntersect.html", "structGEO_1_1FacetIntersect" ],
    [ "FacetsExtraConnectivity", "structGEO_1_1FacetsExtraConnectivity.html", "structGEO_1_1FacetsExtraConnectivity" ],
    [ "FacetsExtraConnectivityWithInvalidFacets", "structGEO_1_1FacetsExtraConnectivityWithInvalidFacets.html", "structGEO_1_1FacetsExtraConnectivityWithInvalidFacets" ],
    [ "Factory", "classGEO_1_1Factory.html", "classGEO_1_1Factory" ],
    [ "Factory0", "classGEO_1_1Factory0.html", null ],
    [ "Factory1", "classGEO_1_1Factory1.html", null ],
    [ "FactoryCreator0", "structGEO_1_1FactoryCreator0.html", "structGEO_1_1FactoryCreator0" ],
    [ "FactoryCreator1", "structGEO_1_1FactoryCreator1.html", "structGEO_1_1FactoryCreator1" ],
    [ "FF_param", "structGEO_1_1FF__param.html", "structGEO_1_1FF__param" ],
    [ "FFopt", "classGEO_1_1FFopt.html", "classGEO_1_1FFopt" ],
    [ "Frame", "structGEO_1_1Frame.html", "structGEO_1_1Frame" ],
    [ "FrameBufferObject", "classGEO_1_1FrameBufferObject.html", "classGEO_1_1FrameBufferObject" ],
    [ "FrameField", "classGEO_1_1FrameField.html", "classGEO_1_1FrameField" ],
    [ "FullScreenEffectImpl", "classGEO_1_1FullScreenEffectImpl.html", "classGEO_1_1FullScreenEffectImpl" ],
    [ "FunctionCommandInvoker", "classGEO_1_1FunctionCommandInvoker.html", "classGEO_1_1FunctionCommandInvoker" ],
    [ "GenColor", "classGEO_1_1GenColor.html", "classGEO_1_1GenColor" ],
    [ "geo_declare_image_serializer", "classGEO_1_1geo__declare__image__serializer.html", "classGEO_1_1geo__declare__image__serializer" ],
    [ "geo_register_attribute_type", "classGEO_1_1geo__register__attribute__type.html", "classGEO_1_1geo__register__attribute__type" ],
    [ "GeoFile", "classGEO_1_1GeoFile.html", "classGEO_1_1GeoFile" ],
    [ "GeoFileException", "classGEO_1_1GeoFileException.html", "classGEO_1_1GeoFileException" ],
    [ "HBoxes", "structGEO_1_1HBoxes.html", "structGEO_1_1HBoxes" ],
    [ "HexdomParam", "structGEO_1_1HexdomParam.html", null ],
    [ "IdPair", "structGEO_1_1IdPair.html", "structGEO_1_1IdPair" ],
    [ "Image", "classGEO_1_1Image.html", "classGEO_1_1Image" ],
    [ "ImageLibrary", "classGEO_1_1ImageLibrary.html", "classGEO_1_1ImageLibrary" ],
    [ "ImageRasterizer", "classGEO_1_1ImageRasterizer.html", "classGEO_1_1ImageRasterizer" ],
    [ "ImageSerializer", "classGEO_1_1ImageSerializer.html", "classGEO_1_1ImageSerializer" ],
    [ "ImageSerializer_pgm", "classGEO_1_1ImageSerializer__pgm.html", "classGEO_1_1ImageSerializer__pgm" ],
    [ "ImageSerializer_xpm", "classGEO_1_1ImageSerializer__xpm.html", "classGEO_1_1ImageSerializer__xpm" ],
    [ "ImageSerializerSTB", "classGEO_1_1ImageSerializerSTB.html", "classGEO_1_1ImageSerializerSTB" ],
    [ "ImageSerializerSTBRead", "classGEO_1_1ImageSerializerSTBRead.html", "classGEO_1_1ImageSerializerSTBRead" ],
    [ "ImageSerializerSTBReadWrite", "classGEO_1_1ImageSerializerSTBReadWrite.html", "classGEO_1_1ImageSerializerSTBReadWrite" ],
    [ "InputGeoFile", "classGEO_1_1InputGeoFile.html", "classGEO_1_1InputGeoFile" ],
    [ "InstanceRepo", "classGEO_1_1InstanceRepo.html", "classGEO_1_1InstanceRepo" ],
    [ "IntegrationSimplex", "classGEO_1_1IntegrationSimplex.html", "classGEO_1_1IntegrationSimplex" ],
    [ "KdTree", "classGEO_1_1KdTree.html", "classGEO_1_1KdTree" ],
    [ "LinearLeastSquares", "classGEO_1_1LinearLeastSquares.html", "classGEO_1_1LinearLeastSquares" ],
    [ "LineInput", "classGEO_1_1LineInput.html", "classGEO_1_1LineInput" ],
    [ "LocalFeatureSize", "classGEO_1_1LocalFeatureSize.html", "classGEO_1_1LocalFeatureSize" ],
    [ "lua_to", "classGEO_1_1lua__to.html", "classGEO_1_1lua__to" ],
    [ "lua_to< bool >", "classGEO_1_1lua__to_3_01bool_01_4.html", "classGEO_1_1lua__to_3_01bool_01_4" ],
    [ "lua_to< const char * >", "classGEO_1_1lua__to_3_01const_01char_01_5_01_4.html", "classGEO_1_1lua__to_3_01const_01char_01_5_01_4" ],
    [ "lua_to< const std::string & >", "classGEO_1_1lua__to_3_01const_01std_1_1string_01_6_01_4.html", "classGEO_1_1lua__to_3_01const_01std_1_1string_01_6_01_4" ],
    [ "lua_to< double >", "classGEO_1_1lua__to_3_01double_01_4.html", "classGEO_1_1lua__to_3_01double_01_4" ],
    [ "lua_to< float >", "classGEO_1_1lua__to_3_01float_01_4.html", "classGEO_1_1lua__to_3_01float_01_4" ],
    [ "lua_to< int >", "classGEO_1_1lua__to_3_01int_01_4.html", "classGEO_1_1lua__to_3_01int_01_4" ],
    [ "lua_to< Numeric::int64 >", "classGEO_1_1lua__to_3_01Numeric_1_1int64_01_4.html", "classGEO_1_1lua__to_3_01Numeric_1_1int64_01_4" ],
    [ "lua_to< Numeric::uint32 >", "classGEO_1_1lua__to_3_01Numeric_1_1uint32_01_4.html", "classGEO_1_1lua__to_3_01Numeric_1_1uint32_01_4" ],
    [ "lua_to< Numeric::uint64 >", "classGEO_1_1lua__to_3_01Numeric_1_1uint64_01_4.html", "classGEO_1_1lua__to_3_01Numeric_1_1uint64_01_4" ],
    [ "lua_to< std::string >", "classGEO_1_1lua__to_3_01std_1_1string_01_4.html", "classGEO_1_1lua__to_3_01std_1_1string_01_4" ],
    [ "lua_wrapper", "classGEO_1_1lua__wrapper.html", null ],
    [ "Matrix", "classGEO_1_1Matrix.html", "classGEO_1_1Matrix" ],
    [ "MatrixM", "structGEO_1_1MatrixM.html", "structGEO_1_1MatrixM" ],
    [ "MatrixMixedConstrainedSolver", "structGEO_1_1MatrixMixedConstrainedSolver.html", "structGEO_1_1MatrixMixedConstrainedSolver" ],
    [ "MemberFunctionCommandInvoker", "classGEO_1_1MemberFunctionCommandInvoker.html", "classGEO_1_1MemberFunctionCommandInvoker" ],
    [ "Mesh", "classGEO_1_1Mesh.html", "classGEO_1_1Mesh" ],
    [ "MeshAABB2d", "classGEO_1_1MeshAABB2d.html", "classGEO_1_1MeshAABB2d" ],
    [ "MeshAABB3d", "classGEO_1_1MeshAABB3d.html", "classGEO_1_1MeshAABB3d" ],
    [ "MeshCellCornersStore", "classGEO_1_1MeshCellCornersStore.html", "classGEO_1_1MeshCellCornersStore" ],
    [ "MeshCellFacetsStore", "classGEO_1_1MeshCellFacetsStore.html", "classGEO_1_1MeshCellFacetsStore" ],
    [ "MeshCells", "classGEO_1_1MeshCells.html", "classGEO_1_1MeshCells" ],
    [ "MeshCellsAABB", "classGEO_1_1MeshCellsAABB.html", "classGEO_1_1MeshCellsAABB" ],
    [ "MeshCellsStore", "classGEO_1_1MeshCellsStore.html", "classGEO_1_1MeshCellsStore" ],
    [ "MeshEdges", "classGEO_1_1MeshEdges.html", "classGEO_1_1MeshEdges" ],
    [ "MeshElements", "classGEO_1_1MeshElements.html", "classGEO_1_1MeshElements" ],
    [ "MeshFacetCornersStore", "classGEO_1_1MeshFacetCornersStore.html", "classGEO_1_1MeshFacetCornersStore" ],
    [ "MeshFacets", "classGEO_1_1MeshFacets.html", "classGEO_1_1MeshFacets" ],
    [ "MeshFacetsAABB", "classGEO_1_1MeshFacetsAABB.html", "classGEO_1_1MeshFacetsAABB" ],
    [ "MeshFacetsAABB2d", "classGEO_1_1MeshFacetsAABB2d.html", "classGEO_1_1MeshFacetsAABB2d" ],
    [ "MeshFacetsStore", "classGEO_1_1MeshFacetsStore.html", "classGEO_1_1MeshFacetsStore" ],
    [ "MeshGfx", "classGEO_1_1MeshGfx.html", "classGEO_1_1MeshGfx" ],
    [ "MeshHalfedges", "classGEO_1_1MeshHalfedges.html", "classGEO_1_1MeshHalfedges" ],
    [ "MeshIOFlags", "classGEO_1_1MeshIOFlags.html", "classGEO_1_1MeshIOFlags" ],
    [ "MeshIOHandler", "classGEO_1_1MeshIOHandler.html", "classGEO_1_1MeshIOHandler" ],
    [ "MeshSplitCallbacks", "classGEO_1_1MeshSplitCallbacks.html", "classGEO_1_1MeshSplitCallbacks" ],
    [ "MeshSubElementsStore", "classGEO_1_1MeshSubElementsStore.html", "classGEO_1_1MeshSubElementsStore" ],
    [ "MeshVertices", "classGEO_1_1MeshVertices.html", "classGEO_1_1MeshVertices" ],
    [ "MonoThreadingThreadManager", "classGEO_1_1MonoThreadingThreadManager.html", "classGEO_1_1MonoThreadingThreadManager" ],
    [ "MorphoMath", "classGEO_1_1MorphoMath.html", "classGEO_1_1MorphoMath" ],
    [ "NaiveSparseMatrix", "structGEO_1_1NaiveSparseMatrix.html", "structGEO_1_1NaiveSparseMatrix" ],
    [ "NearestNeighborSearch", "classGEO_1_1NearestNeighborSearch.html", "classGEO_1_1NearestNeighborSearch" ],
    [ "no_iterator", "classGEO_1_1no__iterator.html", "classGEO_1_1no__iterator" ],
    [ "OptimalTransportMap", "classGEO_1_1OptimalTransportMap.html", "classGEO_1_1OptimalTransportMap" ],
    [ "OptimalTransportMap2d", "classGEO_1_1OptimalTransportMap2d.html", "classGEO_1_1OptimalTransportMap2d" ],
    [ "OptimalTransportMap3d", "classGEO_1_1OptimalTransportMap3d.html", "classGEO_1_1OptimalTransportMap3d" ],
    [ "OptimalTransportMapOnSurface", "classGEO_1_1OptimalTransportMapOnSurface.html", "classGEO_1_1OptimalTransportMapOnSurface" ],
    [ "Optimizer", "classGEO_1_1Optimizer.html", "classGEO_1_1Optimizer" ],
    [ "OutputGeoFile", "classGEO_1_1OutputGeoFile.html", "classGEO_1_1OutputGeoFile" ],
    [ "PackedArrays", "classGEO_1_1PackedArrays.html", "classGEO_1_1PackedArrays" ],
    [ "Packer", "classGEO_1_1Packer.html", "classGEO_1_1Packer" ],
    [ "ParamValidator", "classGEO_1_1ParamValidator.html", "classGEO_1_1ParamValidator" ],
    [ "Periodic", "classGEO_1_1Periodic.html", "classGEO_1_1Periodic" ],
    [ "PeriodicDelaunay3d", "classGEO_1_1PeriodicDelaunay3d.html", "classGEO_1_1PeriodicDelaunay3d" ],
    [ "PGPopt", "classGEO_1_1PGPopt.html", "classGEO_1_1PGPopt" ],
    [ "Plane", "structGEO_1_1Plane.html", "structGEO_1_1Plane" ],
    [ "Poly2d", "structGEO_1_1Poly2d.html", "structGEO_1_1Poly2d" ],
    [ "Poly3d", "structGEO_1_1Poly3d.html", "structGEO_1_1Poly3d" ],
    [ "PrincipalAxes3d", "classGEO_1_1PrincipalAxes3d.html", "classGEO_1_1PrincipalAxes3d" ],
    [ "ProcessorStopwatch", "classGEO_1_1ProcessorStopwatch.html", "classGEO_1_1ProcessorStopwatch" ],
    [ "ProgressClient", "classGEO_1_1ProgressClient.html", "classGEO_1_1ProgressClient" ],
    [ "ProgressTask", "classGEO_1_1ProgressTask.html", "classGEO_1_1ProgressTask" ],
    [ "Quaternion", "classGEO_1_1Quaternion.html", "classGEO_1_1Quaternion" ],
    [ "range", "classGEO_1_1range.html", "classGEO_1_1range" ],
    [ "rational_nt", "classGEO_1_1rational__nt.html", "classGEO_1_1rational__nt" ],
    [ "Ray", "structGEO_1_1Ray.html", "structGEO_1_1Ray" ],
    [ "ReadOnlyScalarAttributeAdapter", "classGEO_1_1ReadOnlyScalarAttributeAdapter.html", "classGEO_1_1ReadOnlyScalarAttributeAdapter" ],
    [ "RegularWeightedDelaunay2d", "classGEO_1_1RegularWeightedDelaunay2d.html", "classGEO_1_1RegularWeightedDelaunay2d" ],
    [ "RegularWeightedDelaunay3d", "classGEO_1_1RegularWeightedDelaunay3d.html", "classGEO_1_1RegularWeightedDelaunay3d" ],
    [ "RemoveColMatrix", "structGEO_1_1RemoveColMatrix.html", "structGEO_1_1RemoveColMatrix" ],
    [ "RestrictedVoronoiDiagram", "classGEO_1_1RestrictedVoronoiDiagram.html", "classGEO_1_1RestrictedVoronoiDiagram" ],
    [ "RVDCallback", "classGEO_1_1RVDCallback.html", "classGEO_1_1RVDCallback" ],
    [ "RVDMeshBuilder", "classGEO_1_1RVDMeshBuilder.html", "classGEO_1_1RVDMeshBuilder" ],
    [ "RVDPolygonCallback", "classGEO_1_1RVDPolygonCallback.html", "classGEO_1_1RVDPolygonCallback" ],
    [ "RVDPolyhedronCallback", "classGEO_1_1RVDPolyhedronCallback.html", "classGEO_1_1RVDPolyhedronCallback" ],
    [ "RVDVertexMap", "classGEO_1_1RVDVertexMap.html", "classGEO_1_1RVDVertexMap" ],
    [ "SimpleApplication", "classGEO_1_1SimpleApplication.html", "classGEO_1_1SimpleApplication" ],
    [ "SimpleMeshApplication", "classGEO_1_1SimpleMeshApplication.html", "classGEO_1_1SimpleMeshApplication" ],
    [ "SmartPointer", "classGEO_1_1SmartPointer.html", "classGEO_1_1SmartPointer" ],
    [ "SphericalHarmonicL4", "structGEO_1_1SphericalHarmonicL4.html", "structGEO_1_1SphericalHarmonicL4" ],
    [ "StatusBar", "classGEO_1_1StatusBar.html", "classGEO_1_1StatusBar" ],
    [ "Stopwatch", "classGEO_1_1Stopwatch.html", "classGEO_1_1Stopwatch" ],
    [ "StructuringElement", "classGEO_1_1StructuringElement.html", "classGEO_1_1StructuringElement" ],
    [ "SystemEnvironment", "classGEO_1_1SystemEnvironment.html", "classGEO_1_1SystemEnvironment" ],
    [ "SystemStopwatch", "classGEO_1_1SystemStopwatch.html", "classGEO_1_1SystemStopwatch" ],
    [ "TaskCanceled", "structGEO_1_1TaskCanceled.html", "structGEO_1_1TaskCanceled" ],
    [ "TextEditor", "classGEO_1_1TextEditor.html", "classGEO_1_1TextEditor" ],
    [ "Thread", "classGEO_1_1Thread.html", "classGEO_1_1Thread" ],
    [ "ThreadManager", "classGEO_1_1ThreadManager.html", "classGEO_1_1ThreadManager" ],
    [ "TrFan", "structGEO_1_1TrFan.html", "structGEO_1_1TrFan" ],
    [ "TrglGradient", "classGEO_1_1TrglGradient.html", "classGEO_1_1TrglGradient" ],
    [ "TypedAttributeStore", "classGEO_1_1TypedAttributeStore.html", "classGEO_1_1TypedAttributeStore" ],
    [ "TypedAttributeStoreCreator", "classGEO_1_1TypedAttributeStoreCreator.html", "classGEO_1_1TypedAttributeStoreCreator" ],
    [ "TypedThreadGroup", "classGEO_1_1TypedThreadGroup.html", "classGEO_1_1TypedThreadGroup" ],
    [ "UncenteredPCA3D", "structGEO_1_1UncenteredPCA3D.html", "structGEO_1_1UncenteredPCA3D" ],
    [ "UnsharpMaskingImpl", "classGEO_1_1UnsharpMaskingImpl.html", "classGEO_1_1UnsharpMaskingImpl" ],
    [ "VariableObserver", "classGEO_1_1VariableObserver.html", "classGEO_1_1VariableObserver" ],
    [ "VariableObserverList", "classGEO_1_1VariableObserverList.html", "classGEO_1_1VariableObserverList" ],
    [ "vecng", "classGEO_1_1vecng.html", "classGEO_1_1vecng" ],
    [ "vecng< 2, T >", "classGEO_1_1vecng_3_012_00_01T_01_4.html", "classGEO_1_1vecng_3_012_00_01T_01_4" ],
    [ "vecng< 3, T >", "classGEO_1_1vecng_3_013_00_01T_01_4.html", "classGEO_1_1vecng_3_013_00_01T_01_4" ],
    [ "vecng< 4, T >", "classGEO_1_1vecng_3_014_00_01T_01_4.html", "classGEO_1_1vecng_3_014_00_01T_01_4" ],
    [ "vector", "classGEO_1_1vector.html", "classGEO_1_1vector" ],
    [ "vector< bool >", "classGEO_1_1vector_3_01bool_01_4.html", "classGEO_1_1vector_3_01bool_01_4" ],
    [ "VSDM", "classGEO_1_1VSDM.html", "classGEO_1_1VSDM" ]
];