name: Doxygen

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Dependencies
        run: |
            sudo apt-get update
            sudo apt-get install \
              xorg-dev  \
              doxygen

      - name: Configure
        run: |
          ./configure.sh

      - name: Build
        run: cd build/Linux64-gcc-dynamic-Release; make doc

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/Linux64-gcc-dynamic-Release/doc/doc/html
